### ISSUE TITLE
Map JSON Data Text

### ISSUE THREAD

**Issue by yukiqt** [Llamaware/IelmenDecryptor#2]
All text is shown as "(label/lines/etc)[randomString]" when run in the browser
![2023-11-24](https://github.com/Llamaware/IelmenDecryptor/assets/83128586/5994813d-1104-4075-a135-33b3a6c71ac9)

**Comment by gBasil** [comment]
I ran into the same issue when making a web port, so I can vouch that this is a legitimate issue, though I don't recall how exactly I fixed it though. However, it's unrelated to decryption, as language files aren't encrypted decrypted.

**Comment by yukiqt** [comment]
reckon you could send me the fixed ver?
Sincerely,
Yuki.
[https://cdn.possum.city/uploads/44792a27-f425-42c0-8499-574b0654623a.gif]

Nov 25, 2023 4:45:32 PM Basil ***@***.***>:

**Comment by gBasil** [comment]
I'd rather not share the webport because of the potential for piracy, but I can share a work-in-progress mod for getting the game to run natively on Linux/macOS, if that's your end goal. Do you have some non-public place I can contact you on (Discord, Matrix, fedi)?

**Comment by yukiqt** [comment]
all contact methods are linked on my site (posm.gay)
Sincerely,
Yuki.
[https://cdn.possum.city/uploads/44792a27-f425-42c0-8499-574b0654623a.gif]

Nov 25, 2023 4:56:00 PM Basil ***@***.***>:

**Comment by gBasil** [comment]
Sent a message on Matrix.

**Comment by gBasil** [comment]
(Issue has been resolved privately)
